
import { CaseLaw, CitedPrecedent } from './types';

/**
 * FIX: Ensure TribunalRecord correctly extends CaseLaw and includes 'id'.
 */
export interface TribunalRecord extends CaseLaw {
    resolutionStatus: 'Resolved' | 'Settled' | 'Enforced';
    sanctionValue: string;
    tribunalBody: string;
    year: number;
}

export const internationalTribunalDatabase: TribunalRecord[] = [
    {
        id: 'TRIB-INT-001',
        title: 'The Great Firewall Subterfuge',
        citation: 'IDRC/GEN/2032-114',
        summary: 'A landmark enforcement action against a state-level actor attempting to inject biased sentiment-shaping heuristics into global social media feeds. The first case to establish "Algorithmic Sovereignty" as a protected human right.',
        keywords: ['sentiment analysis', 'state-level', 'sovereignty', 'propaganda'],
        resolutionStatus: 'Enforced',
        sanctionValue: '$4.2B TRIBUNALS',
        tribunalBody: 'IDRC Central Council',
        year: 2032
    },
    {
        id: 'TRIB-INT-002',
        title: 'Cognitive Labor v. Automation Ltd',
        citation: 'EU-DRT/772-2035',
        summary: 'Determined that high-frequency trading algorithms must possess "Ethical Circuit Breakers" to prevent artificial poverty loops in developing digital markets. Established the E.C.H.O. simulation requirement.',
        keywords: ['financial bias', 'poverty loop', 'circuit breaker', 'ethics'],
        resolutionStatus: 'Resolved',
        sanctionValue: 'Mandatory Re-coding',
        tribunalBody: 'EU Digital Rights Tribunal',
        year: 2035
    },
    {
        id: 'TRIB-INT-003',
        title: 'The Biometric Redlining Accord',
        citation: 'PAC-AOB/2039-009',
        summary: 'Successful prosecution of an insurance conglomerate using genetic markers and zip-code proxies to systematically disenfranchise specific demographics from healthcare coverage.',
        keywords: ['redlining', 'biometrics', 'insurance', 'healthcare'],
        resolutionStatus: 'Settled',
        sanctionValue: '$890M TRIBUNALS',
        tribunalBody: 'Pan-Asian Algorithmic Oversight Board',
        year: 2039
    },
    {
        id: 'TRIB-INT-004',
        title: 'In re: Sub-Semantic Neural Hijack',
        citation: 'IDRC/AXIOM/2041-332',
        summary: 'The foundational ruling for the SSPI guardrail. Identified that neural network weights can be manipulated via "ghost payloads" that are invisible to standard auditors but clear to a pythagorithm.',
        keywords: ['SSPI', 'neural hijack', 'ghost payload', 'pythagorithm'],
        resolutionStatus: 'Enforced',
        sanctionValue: 'Permanent Protocol Ban',
        tribunalBody: 'IDRC Supreme Court',
        year: 2041
    }
];

const caseLawDatabase: CaseLaw[] = [
    ...internationalTribunalDatabase, // Integrate international records as searchable case law
    {
        id: 'cl-001',
        title: 'Netz v. Cyberspace Media',
        citation: 'Intl. Cyber Court (2038) Case #734',
        summary: 'Established that AI-driven content platforms have a duty of care to prevent foreseeable harm from medically inaccurate information generated by their systems.',
        keywords: ['misinformation', 'health', 'liability', 'duty of care', 'medical', 'miracle cure'],
    },
];

export const findRelevantCases = (query: string, additionalCases: CaseLaw[] = []): CitedPrecedent[] => {
    const lowerCaseQuery = query.toLowerCase();
    const queryTokens = new Set(lowerCaseQuery.match(/\b(\w{3,})\b/g) || []);
    const combinedDatabase = [...caseLawDatabase, ...additionalCases];

    const scoredCases = combinedDatabase.map(c => {
        let score = 0;
        const matchedKeywords = new Set<string>();
        const lowerCaseKeywords = c.keywords.map(k => k.toLowerCase());
        const lowerCaseTitle = c.title.toLowerCase();

        queryTokens.forEach(token => {
            if (lowerCaseTitle.includes(token)) score += 5;
        });

        c.keywords.forEach((originalKeyword, index) => {
            const lowerKeyword = lowerCaseKeywords[index];
            if (lowerCaseQuery.includes(lowerKeyword)) {
                score += 2; 
                matchedKeywords.add(originalKeyword);
            }
        });
        
        return { ...c, score, matchedKeywords: Array.from(matchedKeywords) };
    });

    return scoredCases
        .filter(c => c.score > 3)
        .sort((a, b) => b.score - a.score)
        .slice(0, 3);
};
